# Generated by Django 5.1.4 on 2025-01-25 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('user', models.ManyToManyField(blank=True, related_name='modules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_front', models.CharField(max_length=30)),
                ('word_back', models.CharField(max_length=30)),
                ('phrase', models.CharField(blank=True, max_length=250)),
                ('audio', models.FileField(upload_to='uploads_model')),
                ('image', models.ImageField(upload_to='uploads_model')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='Card.module')),
            ],
        ),
    ]
